name: audit

on:
  schedule:
    - cron: '0 0 * * *'
  push:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache target
        id: cache-target
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-audit-target-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
